line-length=126

[per-file-ignores]
"docs/ext/docscrape_sphinx.py" = ["E401"]
"docs/ext/docscrape.py" = ["E701", "E741"]
"docs/ext/numpydoc.py" = ["E401", "E402", "E701"]
"docs/ext/plot2rst.py" = ["E402"]
"docs/source/conf.py" = ["E402"]
"docs/tools/plot_pr.py" = ["E741"]
"setup.py" = ["E402"]
